version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"

  executables:
    restart: always
    build:
      context: ./executables
    expose:
      - "8000"

  web:
    restart: always
    build:
      context: ./website
    ports:
      - "3000:3000"
    depends_on:
      - executables
      - db